In [ ]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense,Activation,Flatten,Dropout
from keras.layers import Conv2D,MaxPooling2D

data=np.load('dataChestXray250.npy')
target=np.load('targetChestXray250.npy')

def loadingCNN():
    model=Sequential()

    model.add(Conv2D(32,(3,3),input_shape=data.shape[1:]))
    model.add(Activation('relu'))
    model.add(BatchNormalization())
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Dropout(0.5))

    model.add(Conv2D(32,(3,3)))
    model.add(Activation('relu'))
    model.add(BatchNormalization())
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Dropout(0.5))

    model.add(Conv2D(64,(3,3)))
    model.add(Activation('relu'))
    model.add(BatchNormalization())
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Dropout(0.5))

    model.add(Conv2D(64,(3,3)))
    model.add(Activation('relu'))
    model.add(BatchNormalization())
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Dropout(0.5))

    model.add(Flatten())

    model.add(Dense(128,activation='relu'))
    model.add(BatchNormalization())
    model.add(Dropout(0.5))

    model.add(Dense(2,activation='softmax'))

    model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
    model.load_weights('ChestXRayPredictions8epochsDropouts.h5')
    return model

loadingCNN()

Using TensorFlow backend.
C:\Users\Ayodhya\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Ayodhya\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Ayodhya\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:

In [49]:
import cv2 as cv
import os
  
testPath='Testimages'
imageNames=os.listdir(testPath)
model=loadingCNN()
category={0:'Normal',1:'Pnemonia'}

for imageName in imageNames:
    imagePath=os.path.join(testPath,imageName)
    image=cv.imread(imagePath)
    grayImage=cv.cvtColor(image,cv.COLOR_BGR2GRAY)
    resized=cv.resize(grayImage,(250,250))
    normalized=resized/255
    reshaped=np.reshape(normalized,(1,250,250,1))
    result=model.predict(reshaped)
    label=np.argmax(result,axis=1)[0]
    prob=np.max(result,axis=1)[0]
    prob=round(prob,2)*100
#image[:50,:]=[0,255,0]
    cv.putText(image,str(category[label]),(100,100),cv.FONT_HERSHEY_SIMPLEX,3,(255,255,255),2)
    cv.putText(image,str(prob),(100,200),cv.FONT_HERSHEY_SIMPLEX,3,(255,255,255),2)
    cv.imshow('LIVE',image)
    cv.waitKey(5000)
    print(result)

[[0.8107613  0.18923871]]
[[0.02574237 0.97425765]]
[[3.0701488e-04 9.9969304e-01]]
[[0.02164662 0.9783533 ]]
[[0.5525064  0.44749364]]
[[0.29930633 0.70069367]]
[[0.9263974  0.07360261]]
[[0.05979208 0.9402079 ]]
[[0.23579775 0.76420224]]
[[0.00516742 0.9948325 ]]
[[0.10143363 0.8985664 ]]
[[5.052030e-04 9.994948e-01]]
[[0.30684412 0.6931558 ]]
[[0.15696223 0.8430377 ]]
[[0.02165517 0.9783448 ]]
[[0.00506452 0.9949356 ]]
[[0.06765868 0.93234134]]
[[0.06826048 0.9317395 ]]
[[0.97769976 0.02230028]]
[[0.38659436 0.61340564]]
[[0.11195702 0.8880429 ]]
[[2.787104e-04 9.997212e-01]]
[[0.48570663 0.5142934 ]]
[[0.14455163 0.85544837]]
[[0.01050743 0.98949254]]
[[0.09587155 0.9041285 ]]
[[1.1470728e-04 9.9988532e-01]]
[[0.47510645 0.5248936 ]]
[[7.2367862e-04 9.9927634e-01]]
[[0.06785909 0.9321409 ]]
[[0.35255036 0.6474497 ]]
[[2.989380e-05 9.999701e-01]]
[[0.00558944 0.9944106 ]]
[[0.04751423 0.9524858 ]]
[[0.00264743 0.9973526 ]]
[[0.76410854 0.23589146]]
[[0.9695887 0.0304113]]
[[0.760867

KeyboardInterrupt: 