In [6]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense,Activation,Flatten,Dropout
from keras.layers import Conv2D,MaxPooling2D

data=np.load('dataChestXray.npy')
target=np.load('targetChestXray.npy')

def loadingCNN():
    model=Sequential()

    model.add(Conv2D(64,(3,3),input_shape=data.shape[1:]))
    model.add(Activation('relu'))
    model.add(Dropout(0.2))
    model.add(MaxPooling2D(pool_size=(2,2)))


    model.add(Conv2D(128,(3,3)))
    model.add(Activation('relu'))
    model.add(Dropout(0.2))
    model.add(MaxPooling2D(pool_size=(2,2)))


    model.add(Conv2D(256,(3,3)))
    model.add(Activation('relu'))
    model.add(Dropout(0.2))
    model.add(MaxPooling2D(pool_size=(2,2)))

    model.add(Flatten())

    model.add(Dense(64,activation='relu'))

    model.add(Dense(2,activation='softmax'))

    model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
    model.load_weights('ChestXRayPredictions8epochsDropouts.h5')
    return model

loadingCNN()

In [ ]:
import cv2 as cv
import os
  
testPath='Testimages'
imageNames=os.listdir(testPath)
model=loadingCNN()
category={0:'Normal',1:'Pnemonia'}

for imageName in imageNames:
    imagePath=os.path.join(testPath,imageName)
    image=cv.imread(imagePath)
    grayImage=cv.cvtColor(image,cv.COLOR_BGR2GRAY)
    resized=cv.resize(grayImage,(128,128))
    normalized=resized/255
    reshaped=np.reshape(normalized,(1,128,128,1))
    result=model.predict(reshaped)
    label=np.argmax(result,axis=1)[0]
    prob=np.max(result,axis=1)[0]
    prob=round(prob,2)*100
#image[:50,:]=[0,255,0]
    cv.putText(image,str(category[label]),(100,100),cv.FONT_HERSHEY_SIMPLEX,3,(255,255,255),2)
    cv.putText(image,str(prob),(100,200),cv.FONT_HERSHEY_SIMPLEX,3,(255,255,255),2)
    cv.imshow('LIVE',image)
    cv.waitKey(5000)
    print(result)

[[0.93160236 0.06839767]]
[[0.16079444 0.83920556]]
[[0.18922164 0.8107784 ]]
[[0.3717809  0.62821907]]
[[0.93990225 0.06009777]]
[[0.83787197 0.1621281 ]]
[[0.93874246 0.0612576 ]]
[[0.3656726 0.6343274]]
[[0.62309295 0.3769071 ]]
[[0.12392263 0.87607735]]
[[0.8286204  0.17137958]]
[[0.05559873 0.9444012 ]]
[[0.8097703  0.19022971]]
[[0.51051927 0.48948073]]
[[0.49409407 0.505906  ]]
[[0.33076876 0.66923124]]
[[0.0159442  0.98405576]]
[[0.06545409 0.934546  ]]
[[0.9267383  0.07326167]]
[[0.7267332 0.2732668]]
[[0.15598662 0.8440134 ]]
[[0.04681674 0.9531833 ]]
[[0.6671356  0.33286446]]
[[0.3140229 0.6859771]]
[[0.22405851 0.7759415 ]]
[[0.4971003 0.5028997]]
[[0.03316887 0.96683115]]
[[0.87554437 0.12445568]]
[[0.04778473 0.95221525]]
[[0.56516665 0.4348334 ]]
[[0.61811787 0.38188213]]
[[0.01003427 0.9899657 ]]
[[0.1158228 0.8841772]]
[[0.3416988 0.6583012]]
[[0.18721612 0.81278384]]
[[0.75942385 0.24057613]]
[[0.9498226  0.05017742]]
[[0.7961159 0.2038841]]
[[0.5860604  0.41393957]]
